# Generated by Django 5.2.7 on 2026-07-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PenguinObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_length_mm", models.FloatField()),
                ("bill_depth_mm", models.FloatField()),
                ("flipper_length_mm", models.FloatField()),
                ("body_mass_g", models.FloatField()),
                (
                    "predicted_species",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
